#!/usr/bin/env csi4 -script

(require-library chicken-doc-admin)

(define (usage)
  (print "usage: " (program-name) " COMMAND")
  (print "  -r        regenerate indices")
  (print "  -l        list repository information")
  (print "  -i        initialize repository non-destructively")
  (print "  -d path   delete key path recursively (EMPTY PATH DELETES ENTIRE REPO)")
  (print "  -e dir    process svnwiki egg directory DIR")
  (print "  -m dir    process svnwiki manual directory DIR")
  (exit))

(when (null? (command-line-arguments))
  (usage))

(let ((o (car (command-line-arguments))))
  (cond ((string=? o "-i")
         (create-repository!))
        (else
         (unless (verify-repository)
           (fprintf (current-error-port)
                    "No repository found at ~a\nUse -i to initialize\n" (repository-base))
           (exit 1))
         (cond ((string=? o "-r")
                (print "Rebuilding ID cache...")
                (refresh-id-cache))
               ((string=? o "-l")
                (describe-repository))
               ((string=? o "-d")
                (delete-key (map string->symbol
                                 (cdr (command-line-arguments)))))
               ((string=? o "-e")
                (unless (pair? (cdr (command-line-arguments)))
                  (usage))
                (parse-egg-directory (cadr (command-line-arguments))
                                     'svnwiki))
               ((string=? o "-m")
                (unless (pair? (cdr (command-line-arguments)))
                  (usage))
                (parse-man-directory (cadr (command-line-arguments))
                                     'svnwiki))
               (else
                (usage))))))
